### ISSUE TITLE
Issues with current versions of react-native and dependencies

### ISSUE THREAD

**Issue by simonexmachina** [nolanlawson/pouchdb-async-storage#6]
Here's the steps I went through trying to get this to work:
- Fixed `Requiring unknown module "request"` error by changing `"request": "./lib/deps/ajax/request-browser.js"` to `./pouchdb/lib/deps/ajax/request-browser.js` in `node_modules/pouchdb/package.json`
- Fixed `Object.prototype may only be an object or null` from `require('pouchdb-async-storage')` by changing `util.inherits(DeferredLevelDOWN, AbstractLevelDOWN)` to `util.inherits(DeferredLevelDOWN, AbstractLevelDOWN.AbstractLevelDOWN)` in `node_modules/levelup/node_modules/deferred-leveldown/deferred-leveldown.js`

Now I have no errors when when I run my app, and I do get a PouchDB instance back when I call `new PouchDB('pomo', {adapter: 'asyncstorage'})`. However when I call `db.put({}, 'test').then(doc => console.log(doc), err => console.error(err))` the promise never resolves.

I've tried with Node v5.0.0 and v5.1.0.

**Comment by nolanlawson** [comment]
Can you please provide a pull request, if you've managed to fix it?

The `request-browser` thingie seems like a weird subtle difference between Webpack and Browserify. But Webpack works with PouchDB AFAIK, so maybe it's a bug in React Native. Not sure. In either case, it would be a bugfix for PouchDB: http://github.com/pouchdb/pouchdb

The DeferredLevelDOWN stuff applies to leveldown. You might want to file a bug over there: https://github.com/Level/leveldown

In general, if you're wondering why this is happening, it's because 99.9% of everybody involved in the PouchDB/LevelDB ecosystem is using Browserify, whereas Webpack has weird subtle differences that nobody has taken the time to address. If you wanted to take that up, you would be doing us all a big favor. :)

**Comment by simonexmachina** [comment]
Our app moved to a different solution for synchronisation, so we're not using this any more. I certainly will do if I pick it up again, but working on other things right now. Thanks for the response.

**Comment by yonahforst** [comment]
I was having the same issue. changing `"request": "./lib/deps/ajax/request-browser.js"` to `./pouchdb/lib/deps/ajax/request-browser.js` in `myproject/node_modules/pouchdb-async-storage/node_modules/pouchdb/package.json` worked for me.

I'll gladly submit a PR but it will have to be on the `pouchdb` repo not `pouchdb-async-storage`. I don't know if this will break anything for the web, while fixing it for react_native...

**Comment by yonahforst** [comment]
well, now i'm running into the second issue where promises never resolve
